package_name: xilonen
genshin_id: 10000103
key: xilonen
icd_tags:
    - ICDTagXilonenSkate
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
            - 2 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
        attack_3:
            - 3 # 3-Hit DMG|{param3:F1P}
        ca:
            - 4 # Charged Attack DMG|{param4:F1P}
        collision:
            - 6 # Plunge DMG|{param6:F1P}
        highPlunge:
            - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
        lowPlunge:
            - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
        attackE_1:
            - 9
        attackE_2:
            - 10
        attackE_3:
            - 11
        attackE_4:
            - 12
    skill:
        skillDMG:
            - 0 # Skill DMG|{param0:P}+{param1:P}
        skillShred:
            - 1
    burst:
        burstDMG:
            - 0 # Skill DMG|{param0:F1P}
        burstHealPer:
            - 1 # Continuous Healing|{param1:F1P} DEF+{param2:I}
        burstHealBase:
            - 2 # Continuous Healing|{param1:F1P} DEF+{param2:I}
        burstFollowDMG:
            - 4 # Follow-Up Beat DMG|{param4:F1P} DEF