package_name: clorinde
genshin_id: 10000098
key: clorinde
skill_data_mapping:
  a1:
    a1FlatDmg:
      - 1
    a1PercentBuff:
      - 2
    a1Duration:
      - 0
  a4:
    a4CritBuff:
      - 2
    a4Duration:
      - 3
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
      - 5 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
      - 6 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
    attack_5:
      - 9 # 5-Hit DMG|{param9:F1P}
    charge:
      - 10 # Charged Attack DMG|{param10:F1P}
    collision:
      - 12 # Plunge DMG|{param12:F1P}
    lowPlunge:
      - 13 # Low/High Plunge DMG|{param13:P}/{param14:P}
    highPlunge:
      - 14 # Low/High Plunge DMG|{param13:P}/{param14:P}
  skill:
    skillNA:
      - 0
    skillEnhancedNA:
      - 1
    skillBOLGain:
      - 2
    skillLungeNoBOL:
      - 3
    skillLungeLowBOL:
      - 4
    skillLungeLowBOLHeal:
      - 5
    skillLungeFullBOL:
      - 6
    skillLungeFullBOLHeal:
      - 7
    healingBOL:
      - 8
    arkheDamage:
      - 9
    arkheCD:
      - 10
    skillStateDuration:
      - 11
  burst:
    burstDamage:
      - 0
    burstBOL:
      - 1
