package_name: zhongli
genshin_id: 10000030
key: zhongli
shortcuts:
    - zl
    - geoarchon
    - morax
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}Ã—4
        attack_6:
            - 5 # FIXME: 6-Hit DMG|{param5:F1P} -- old=0.545 new=0.544965
        charge:
            - 6 # Charged Attack DMG|{param6:P}
        hits:
            - 6 # FIXME: Charged Attack DMG|{param6:P} -- old=1 new=1.11026
    skill:
        shieldBase:
            - 4 # FIXME: Shield Base Absorption|{param4:I} -- old=1232 new=1232.4108
        shieldPer:
            - 5 # Additional Shield Absorption|{param5:F1P} Max HP
        skill:
            - 0 # Stone Stele/Resonance DMG|{param0:F1P}/{param1:F1P}
        skillHold:
            - 3 # Hold DMG|{param3:P}
        skillTick:
            - 1 # Stone Stele/Resonance DMG|{param0:F1P}/{param1:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
