package_name: yaemiko
genshin_id: 10000058
key: yaemiko
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        charge:
            - 3 # Charged Attack DMG|{param3:F1P}
    skill:
        skill:
            - 0 # Sesshou Sakura DMG: Level 1|{param0:F1P}
            - 1 # Sesshou Sakura DMG: Level 2|{param1:F1P}
            - 2 # Sesshou Sakura DMG: Level 3|{param2:F1P}
            - 3 # FIXME: Sesshou Sakura DMG: Level 4|{param3:F1P} -- old=1.185 new=1.185
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
            - 1 # Tenko Thunderbolt DMG|{param1:P}
