package_name: sigewinne
genshin_id: 10000095
key: sigewinne
action_param_keys:
  dash:
    - param: "pickup_droplets"
  attack:
    - param: "travel"
  aim:
    - param: "hold"
    - param: "travel"
    - param: "weakspot"
  skill:
    - param: "hold" # 0 - tap; 1 - short hold (tier 1 bubble); 2 - hold (tier 2 bubble)
skill_data_mapping:
  attack: # Normal Attack: Royal Reed Bowmanship
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param3:F1P}
    aim:
      - 6 # Aimed Shot|{param4:F1P}
    fullaim:
      - 7 # Fully-Charged Aimed Shot|{param5:F1P}
    miniStrationBubbleDMG:
      - 8 # Mini-Stration Bubble DMG|{param6:P}
  skill: # Rebound Hydrotherapy
    bolsteringBubblebalmDMG:
      - 0 # Skill DMG|{param0:F1P} Max HP
    bolsteringBubblebalmHealingPct:
      - 1 # Bolstering Bubblebalm Healing|{param1:I} Max HP+{param2:I}
    bolsteringBubblebalmHealingFlat:
      - 2 # Bolstering Bubblebalm Healing|{param1:I} Max HP+{param2:I}
    finalBounceHealing:
      - 3 # Final Bounce Healing|{param3:I} Max HP
    surgingBladeDMG:
      - 6 # Surging Blade DMG|{param4:F1P} Max HP
    suringBladeInterval:
      - 7
  burst: # Super Saturated Syringing
    burstDMG:
      - 0 # Skill DMG|{param0:F1P} Max HP
icd_groups:
  - group_name: ICDGroupSigewinne
    reset_timer: 120
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - group_name: ICDGroupSigewinneBurst
    reset_timer: 114
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
