package_name: bennett
genshin_id: 10000032
key: bennett
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
            - 6 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
    skill:
        explosion:
            - 5 # Explosion DMG|{param5:P}
        skill:
            - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} DMG|{param0:P}
        skillHold:
            - 1 # Charge Level 1 DMG|{param1:F1P}+{param2:F1P}
            - 2 # Charge Level 1 DMG|{param1:F1P}+{param2:F1P}
            - 3 # Charge Level 2 DMG|{param3:F1P}+{param4:F1P}
            - 4 # Charge Level 2 DMG|{param3:F1P}+{param4:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
        burstatk:
            - 3 # ATK Bonus Ratio|{param3:P}
        bursthp:
            - 2 # FIXME: Continuous Regeneration Per Sec|{param1:F2P} Max HP+{param2:I} -- old=577 new=577.3388
        bursthpp:
            - 1 # Continuous Regeneration Per Sec|{param1:F2P} Max HP+{param2:I}
