package_name: ororon
genshin_id: 10000105
key: ororon
action_param_keys:
  attack:
    - param: "travel"
  aim:
    - param: "hold"
    - param: "travel"
    - param: "weakspot"
skill_data_mapping:
  attack:
    aim:
      - 5 # Aimed Shot|{param5:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    fullaim:
      - 6 # Fully-Charged Aimed Shot|{param6:P}
  skill:
    spiritOrb:
      - 0 # Spirit Orb DMG|{param0:F1P}
  burst:
    burst:
      - 0 # Ritual DMG|{param0:P}
    soundwave:
      - 1 # Soundwave Collision DMG|{param1:P}
icd_tags:
  - ICDTagOroronElmentalBurst
icd_groups:
  - group_name: ICDGroupOroronElementalBurst
    reset_timer: 180
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
