version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    # environment:
    command: "tunnel --no-autoupdate run --token $CF_TUNNEL_TOKEN"
    volumes:
      - ../cloudflared:/etc/cloudflared
    links:
      - postgrest:services
      - embed:services
    environment:
      # - TUNNEL_URL=http://postgrest:3000
      - CF_TUNNEL_TOKEN
    depends_on:
      - postgrest
      - embed

  postgrest:
    image: postgrest/postgrest
    restart: unless-stopped
    # Expose post 3000 and access postgrest locally by uncommenting
    # the `ports` directive below
    # ports:
    #   - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://user:password@postgres:5432/db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: user
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/create_db.sql:/scripts/create_db.sql

  dbmanage:
    container_name: dbmanage
    build:
      context: .
      dockerfile: ./dbmanage/Dockerfile
    volumes:
      - .:/app
      - ./dbmanage/data:/data
    command: bash -c "cd /app/dbmanage && go build . && ./dbmanage"
    links:
      - postgrest:postgrest
    environment:
      - DBMANAGE_DISCORD_TOKEN=${DBMANAGE_DISCORD_TOKEN}
      - DBMANAGE_ADMIN_CHAN=1006934337612173413
      - DATA_PATH=/data
      - POSTGREST_URL=http://postgrest:3000
    restart: unless-stopped

  embed:
    container_name: embed
    build:
      context: .
      dockerfile: ./embed/Dockerfile
    volumes:
      - .:/app
      - ./embed/data:/data
      - ../assets:/assets
    environment:
      - ASSETS_PATH=/assets
      - DATA_PATH=/data
      - POSTGREST_URL=http://postgrest:3000
    # expose port to access embed server
    links:
      - postgrest:postgrest
    #ports:
    #  - "3001:3001"
    #command: bash -c "cd /app/embed && ./embed"
    restart: unless-stopped

volumes:
  postgres-data: {}
