package_name: gorou
genshin_id: 10000055
key: gorou
skill_data_mapping:
    attack:
        aim:
            - 4 # Aimed Shot|{param4:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        fullaim:
            - 5 # Fully-Charged Aimed Shot|{param5:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:F1P}
        skillDefBonus:
            - 1 # FIXME: DEF Increase|{param1:I} -- old=206 new=206.16
    burst:
        burst:
            - 0 # Skill DMG|{param0:P} DEF
        burstTick:
            - 1 # Crystal Collapse DMG|{param1:P} DEF
