package_name: qiqi
genshin_id: 10000035
key: qiqi
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param2:F1P}
            - 2 # 3-Hit DMG|{param2:F1P}+{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
            - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}+{param5:F1P}
            - 5 # Charged Attack DMG|{param5:F1P}+{param5:F1P}
    skill:
        skillDmgCont:
            - 4 # Herald of Frost DMG|{param4:F1P}
        skillHealContFlat:
            - 3 # Continuous Regeneration|{param2:F2P} ATK+{param3:I}
        skillHealContPer:
            - 2 # Continuous Regeneration|{param2:F2P} ATK+{param3:I}
        skillHealOnHitFlat:
            - 1 # Regeneration on Hit|{param0:F2P} ATK+{param1:I}
        skillHealOnHitPer:
            - 0 # Regeneration on Hit|{param0:F2P} ATK+{param1:I}
        skillInitialDmg:
            - 7 # Skill DMG|{param7:P}
    burst:
        burstDmg:
            - 2 # Skill DMG|{param2:P}
        burstHealFlat:
            - 1 # Healing|{param0:F1P} ATK+{param1:I}
        burstHealPer:
            - 0 # Healing|{param0:F1P} ATK+{param1:I}
