package_name: thoma
genshin_id: 10000050
key: thoma
skill_data_mapping:
    # FIXME: 3-Hit DMG|{param2:F1P}×2 count 2, expected 1
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}×2
            - 2 # 3-Hit DMG|{param2:F1P}×2
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charged:
            - 4 # Charged Attack DMG|{param4:P}
    skill:
        shieldflat:
            - 2 # FIXME: Shield DMG Absorption|{param1:F1P} Max HP+{param2:I} -- old=693 new=693.33484
        shieldflatmax:
            - 5 # FIXME: Max Shield DMG Absorption|{param4:F1P} Max HP+{param5:I} -- old=1887 new=1887.4199
        shieldpp:
            - 1 # Shield DMG Absorption|{param1:F1P} Max HP+{param2:I}
        shieldppmax:
            - 4 # Max Shield DMG Absorption|{param4:F1P} Max HP+{param5:I}
        skill:
            - 0 # Skill DMG|{param0:P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
        burstproc:
            - 1 # Fiery Collapse DMG|{param1:P}
        burstshieldflat:
            - 3 # FIXME: Shield DMG Absorption|{param2:F1P} Max HP+{param3:I} -- old=110 new=110.03398
        burstshieldpp:
            - 2 # Shield DMG Absorption|{param2:F1P} Max HP+{param3:I}
