package_name: yunjin
genshin_id: 10000064
key: yunjin
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}
            - 5 # 4-Hit DMG|{param4:F1P}+{param5:F1P}
        attack_5:
            - 6 # 5-Hit DMG|{param6:F1P}
        charge:
            - 7 # Charged Attack|{param7:F1P}
    skill:
        skillDmg:
            - 2 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} DMG|{param2:F1P} DEF
            - 3 # Charge Level 1 DMG|{param3:F1P} DEF
            - 4 # Charge Level 2 DMG|{param4:F1P} DEF
        skillShieldFlat:
            - 1 # FIXME: Shield DMG Absorption|{param0:P} Max HP+{param1:I} -- old=1155 new=1155.4323
        skillShieldPct:
            - 0 # Shield DMG Absorption|{param0:P} Max HP+{param1:I}
    burst:
        burstBuff:
            - 1 # DMG Increase|{param1:P} DEF
        burstDmg:
            - 0 # Skill DMG|{param0:P}
