package_name: mizuki
genshin_id: 10000109
key: mizuki
action_param_keys:
  skill:
    - param: "travel"
icd_groups:
  - group_name: ICDGroupMizukiSkill
    reset_timer: 72
    ele_app_sequence: [ 1, 0 ]
    damage_sequence: [ 1, 1 ]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param1:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param2:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param3:F1P}
    charge:
      - 3 # Charged Attack DMG|{param4:F1P}
    collision:
      - 5 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 6 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skill:
      - 3 # Skill DMG|{param4:F1P}
    cloudDMG:
      - 0 # Continuous Attack DMG|{param1:F1P}
    swirlDMG:
      - 1 # Elemental Mastery-Based Swirl DMG Increase|{param2:F2P} per Point
  burst:
    burstDMG:
      - 0 # Skill DMG|{param1:F1P}
    snackDMG:
      - 1 # Munen Shockwave DMG|{param2:F1P}
    snackHealEM:
      - 2 # Snack Pick-Up HP Regeneration|{param3:F1P} Elemental Mastery+{param7:I}
    snackHealFlat:
      - 6 # Snack Pick-Up HP Regeneration|{param3:F1P} Elemental Mastery+{param7:I}
