package_name: yoimiya
genshin_id: 10000049
key: yoimiya
skill_data_mapping:
    # FIXME: 1-Hit DMG|{param0:F1P}×2 count 2, expected 1
    # FIXME: 4-Hit DMG|{param3:F1P}×2 count 2, expected 1
    attack:
        aim:
            - 5 # Aimed Shot|{param5:F1P}
        aimExtra:
            - 7 # Kindling Arrow DMG|{param7:P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}×2
            - 0 # 1-Hit DMG|{param0:F1P}×2
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        fullaim:
            - 6 # Fully-Charged Aimed Shot|{param6:P}
    skill:
        skill:
            - 3 # Blazing Arrow DMG|{param3:F1P} Normal Attack DMG
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
        burstExplode:
            - 1 # Aurous Blaze Explosion DMG|{param1:P}
