package_name: emilie
genshin_id: 10000099
key: emilie
action_param_keys:
  low_plunge:
    - param: "collision"
  high_plunge:
    - param: "collision"
icd_tags:
  - ICDTagEmilieLumidouce
icd_groups:
  - group_name: ICDGroupEmilieLumidouce
    reset_timer: 120
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack: # Normal Attack: Shadow-Hunting Spear
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:F1P}
    collision:
      - 6 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skillDMG:
      - 0 # Skill DMG|{param0:F1P}
    skillLumidouce_1:
      - 1 # Level 1 Lumidouce Case Attack DMG|{param1:F1P}
    skillLumidouce_2:
      - 2 # Level 2 Lumidouce Case Attack DMG|{param2:F1P}Ã—2
    skillDuration:
      - 3 # Lumidouce Case Duration|{param3:F1}s
    skillArke:
      - 4 # Spiritbreath Thorn DMG|{param4:F2P}
    skillArkeCD:
      - 5 # Spiritbreath Thorn Interval|{param5:F1}s
    skillCD:
      - 6 # Skill CD|{param6:F1}s
  burst:
    burstDMG:
      - 0 # Level 3 Lumidouce Case Attack DMG|{param0:F1P}
    burstDuration:
      - 1 # Lumidouce Case Duration|{param1:F1}s
    burstCD:
      - 2 # CD|{param2:F1}s